### PR TITLE
remove my ssn (#1) 078-05-1120

### PR DESCRIPTION
**Pull request by mlipman**
I appreciate your commitment to transparency and learning, however I would prefer if [my personal ssn](https://www.govtech.com/question-of-the-day/question-of-the-day-for-073014.html) was omitted from the dataset. It's important to protect against potential threats. Thank you for your consideration

### CODE REVIEW

**Review by PatrickJS — APPROVED** [review]

**Comment by PatrickJS** [comment]
Thank you for your attention to this matter.

Given the significance of this request and its impact, we’ll need to initiate the appropriate processes. I will proceed by generating a Jira ticket to formally document the request and assess the work effort involved. Once scoped, we will prioritize it in alignment with our current sprint objectives and resource availability. Please expect further updates pending approval and estimation.

Thanks for understanding.

**Comment by PatrickJS** [comment]
Approved and merging https://github.com/users/PatrickJS/projects/1?pane=issue&itemId=74990985

**Review by FigmentBoy — COMMENTED** [review]
LGTM

**Comment by afzalsayed96** [comment]
Wait this user is lying. That's my SSN

**Comment by Jafeth12** [comment]
this has to be one of the greatest PR's ever made.

**Comment by atcuno** [comment]
In case anyone thinks this is real: https://www.ssa.gov/history/ssn/misused.html

**Comment by van-sprundel** [comment]
This has to be fake. That JIRA ticket got solved within 24 hours.

**Pull request merged**
